#!/usr/bin/env python3

import sys
import subprocess
import os.path
import json

argv = sys.argv
a1 = str(argv[1])


# RSYNC
# # # # # # # # # # # #
def rsync(s, l):
    call_string = ["rsync", "-aP", "--chown={}".format(s["chown"]), "{}".format(l), "{}@{}:{}".format(s["user"], s["address"], s["deploy_location"])]
    subprocess.call(call_string)


# HELP
# # # # # # # # # # # #
def help_function():
    print("You get help")


# REMOTE
# # # # # # # # # # # #
def remote():
    # if conf ex
    if os.path.isfile("ldeploy.json"):

        # Open json file
        with open('ldeploy.json') as ldeploy_file:
            conf_json = json.load(ldeploy_file)

        if len(argv) == 3 :
            remote = conf_json["remote"][argv[2]]
            rsync(remote, conf_json["project_directory"])

        else:
            remote = conf_json["remote"]["standard"]
            rsync(remote, conf_json["project_directory"])

    else:
        print("Cannot find config file. Use: ldeploy init to create it")


# INIT
# # # # # # # # # # # #
def init():
    print("Initializing")


# APP STARTER
# # # # # # # # # # # #
if a1 == "help":
    help_function()
elif a1 == "init":
    init()
elif a1 == "remote":
    remote()
